language: rust
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y gcc g++ make upx electric-fence libsdl1.2debian
script:
  - cargo build --verbose
  - cargo test --verbose
